---
# File: tasks/main.yml - Meatspace Chat v2 role main tasks

- name: Update OS package cache
  sudo: True
  apt: update-cache=yes
  tags:
    - system_packages

- name: Install OS packages
  sudo: True
  apt: pkg={{ item }} state=installed
  with_items: meatspace_chat_v2_os_packages
  tags:
    - system_packages

- name: Create bin dir
  sudo: False
  file: path={{ meatspace_chat_v2_bin_dir}} state=directory owner={{ meatspace_chat_v2_admin }} mode=0755

- name: Create src dir
  sudo: False
  file: path={{ meatspace_chat_v2_src_dir }} state=directory owner={{ meatspace_chat_v2_admin }} mode=0755

- name: Download libvpx
  sudo: False
  get_url: url=http://webm.googlecode.com/files/libvpx-v1.3.0.tar.bz2 dest={{ meatspace_chat_v2_src_dir }}/ mode=0644

- name: Unpack libvpx
  sudo: False
  unarchive: src={{ meatspace_chat_v2_src_dir }}/libvpx-v1.3.0.tar.bz2 dest={{ meatspace_chat_v2_src_dir }}/ copy=no

- name: Configure libvpx
  sudo: False
  shell: ./configure --prefix={{ meatspace_chat_v2_ffmpeg_dir }} --disable-examples chdir={{ meatspace_chat_v2_src_dir }}/libvpx-v1.3.0

- name: Make libvpx
  sudo: False
  shell: make chdir={{ meatspace_chat_v2_src_dir }}/libvpx-v1.3.0

- name: Install libvpx
  sudo: True
  shell: make install chdir={{ meatspace_chat_v2_src_dir }}/libvpx-v1.3.0

- name: Download fdk-aac
  sudo: False
  get_url: url={{ meatspace_chat_v2_fdk_acc_url }} dest={{ meatspace_chat_v2_src_dir }}/ mode=0644

- name: Unpack fdk-aac
  sudo: False
  unarchive: src={{ meatspace_chat_v2_src_dir }}/{{ meatspace_chat_v2_fdk_acc_zip }} dest={{ meatspace_chat_v2_src_dir }}/ copy=no

- name: Prepare fdk-aac
  sudo: False
  shell: cd {{ meatspace_chat_v2_fdk_aac_dir }} && autoreconf -fiv

- name: Configure fdk-aac
  sudo: False
  shell: cd {{ meatspace_chat_v2_fdk_aac_dir }} && ./configure --prefix={{ meatspace_chat_v2_ffmpeg_dir }} --disable-shared

- name: Make fdk-aac
  sudo: False
  shell: cd {{ meatspace_chat_v2_fdk_aac_dir }} && make

- name: Install fdk-aac
  sudo: True
  shell: cd {{ meatspace_chat_v2_fdk_aac_dir }} && make install

- name: Download ffmpeg
  sudo: False
  get_url: url=http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 dest={{ meatspace_chat_v2_src_dir }}/ mode=0644

- name: Unpack ffmpeg
  sudo: False
  unarchive: src={{ meatspace_chat_v2_src_dir }}/ffmpeg-snapshot.tar.bz2 dest={{ meatspace_chat_v2_src_dir }}/ copy=no

- name: Configure ffmpeg
  sudo: False
  shell: PKG_CONFIG_PATH={{ meatspace_chat_v2_home_dir }}/ffmpeg/lib/pkgconfig ./configure --prefix={{ meatspace_chat_v2_home_dir }}/ffmpeg --extra-cflags=-I{{ meatspace_chat_v2_home_dir }}/ffmpeg/include --extra-ldflags=-L{{ meatspace_chat_v2_home_dir }}/ffmpeg/lib --bindir={{ meatspace_chat_v2_home_dir }}/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree chdir={{ meatspace_chat_v2_src_dir }}/ffmpeg

- name: Install ffmpeg
  sudo: True
  shell: make install chdir={{ meatspace_chat_v2_src_dir }}/ffmpeg

- name: Install Node Version Manager (NVM)
  sudo: False
  git: repo=https://{{ meatspace_chat_v2_nvm_repo }} dest={{ meatspace_chat_v2_nvm_dir }} accept_hostkey=True
  tags:
    - node_packages

- name: Install Node.js
  sudo: False
  shell: source {{ meatspace_chat_v2_nvm_dir }}/nvm.sh && nvm install {{ meatspace_chat_v2_node_version }} creates={{ meatspace_chat_v2_node_dir }} executable=/bin/bash
  tags:
    - node_packages

- name: Meatspace Chat v2 home
  sudo: False
  file: path={{ meatspace_chat_v2_app_dir }} state=directory owner={{ meatspace_chat_v2_admin }} mode=0755

- name: Clone Meatspace Chat v2
  sudo: False
  git: repo=git://{{ meatspace_chat_v2_repo }} dest={{ meatspace_chat_v2_app_dir }} accept_hostkey=True

- name: Replace Meatspace Chat package.json
  sudo: False
  copy: src=meatspace-chat-v2-package.json dest={{ meatspace_chat_v2_app_dir }}/package.json owner={{ meatspace_chat_v2_admin }} group={{ meatspace_chat_v2_admin }} mode=0644 force=yes
  tags:
    - node_packages

- name: Install local Node packages
  sudo: False
  npm: path={{ meatspace_chat_v2_app_dir }} executable={{ meatspace_chat_v2_nvm_dir }}/v{{ meatspace_chat_v2_node_version }}/bin/npm state=present
  tags:
    - node_packages

- name: Meatspace Chat v2 settings
  sudo: False
  template: src=local.json.j2 dest={{ meatspace_chat_v2_app_dir }}/local.json owner={{ meatspace_chat_v2_admin }} group={{ meatspace_chat_v2_admin }} mode=0644

- name: Create upstart configuration
  sudo: True
  template: src=meatspace-chat.conf.j2 dest=/etc/init/meatspace-chat.conf

- name: Create upstart script
  sudo: True
  template: src=start_meatspace-chat.sh.j2 dest={{ meatspace_chat_v2_app_dir }}/start_meatspace-chat.sh mode=0755

- name: Start Meatspace Chat v2
  sudo: True
  service: name=meatspace-chat state=restarted
  tags:
    - meatspace_chat_v2_service
