# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile for bootstrapping a Meatspace Chat instance on Mac OS X with
# Vagrant provider and Ansible provisioiner on Ubuntu virtual machine

VAGRANTFILE_API_VERSION = "2"
BOX_MEM = ENV['BOX_MEM'] || "1024"
#BOX_NAME =  ENV['BOX_NAME'] || "precise64"
#BOX_URI = ENV['BOX_URI'] || "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
BOT_HOST = ENV['BOT_HOST'] || "vagrant_hosts"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :meatspacechatv2 do |meatspacechatv2_config|
    meatspacechatv2_config.vm.box = "cargomedia/debian-7-amd64-plain"
    #meatspacechatv2_config.vm.box = BOX_NAME
    #meatspacechatv2_config.vm.box_url = BOX_URI
    meatspacechatv2_config.vm.network :private_network, ip: "10.1.1.40"
    meatspacechatv2_config.vm.hostname = "meatspacechatv2.local"
    meatspacechatv2_config.ssh.forward_agent = true
    meatspacechatv2_config.vm.provider "virtualbox" do |v|
      v.name = "meatspacechatv2"
      v.customize ["modifyvm", :id, "--memory", BOX_MEM]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    meatspacechatv2_config.vm.provision :ansible do |ansible|
      ansible.inventory_path = BOT_HOST
      ansible.playbook = "site.yml"
      ansible.limit = "all"
    end
  end
end
